replicaCount: 2

image:
  repository: nginx # overridden by pipeline
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80
  targetPort: 3000

ingress:
  enabled: true
  className: alb
  annotations:
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
  hosts:
  - host: hello.${YOUR_DOMAIN} # replace or set via pipeline
    paths:
    - path: /
      pathType: Prefix
  tls: [] # can wire ACM certs later
